<?php if ($this->getIsProcessed()):?>
    <?php if ($this->getIsSuccess()):?>
        <h2><?php echo $this->helper('fi_checkout')->__('Verification successful') ?></h2>
        <p><?php echo $this->helper('fi_checkout')->__('Please continue with placing order') ?></p>
        <script type="text/javascript">
            //<![CDATA[
                window.parent.CentinelAuthenticateController.success();
            //]]>
        </script>
    <?php else:?>
        <h4><?php echo $this->__('Verification Failed');?></h4>
        <p><?php echo $this->__('The card has failed verification with the issuer bank.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
    <?php endif;?>
<?php else:?>
    <h4><?php echo $this->__('Verification cannot be processed');?></h4>
    <p><?php echo $this->__('There has been wrong payment information submitted or the time limit has expired. Please, try again.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
<?php endif;?>
