<form action="" id="checkout-agreements" onsubmit="return false;">
<?php if ($this->getAgreements()): ?>
    <ol class="checkout-agreements" id="easyco-agreements">
    <?php foreach ($this->getAgreements() as $_a): ?>
        <li class="relative">
            <div class="popup agreement-popup" style="display:none" id="agree-<?php echo $_a->getId()?>">
                <div class="popup-arrow"></div>
                <div class="popup-heading">
                    <h2><?php echo $this->htmlEscape($_a->getCheckboxText()) ?></h2>
                </div>
                <div class="popup-content"<?php echo $_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '' ?>>
                <?php if ($_a->getIsHtml()):?>
                    <?php echo $_a->getContent() ?>
                <?php else:?>
                    <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                <?php endif; ?>
                </div>
            </div>
            <div class="total-field">
                <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox required-entry" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $this->__('I accept the') ?> <a href="#agree-<?php echo $_a->getId()?>" onclick="var c=$(this).up('div').previous();c.offsetHeight ? c.hide() : c.show();return false"><?php echo $this->__('Terms and Conditions') ?></a> <em>*</em></label>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
<?php endif ?>
</form>
